export enum CharacterAnimationName {
  IDLE = "idle",
  START_BACK_LEFT = "start_back_left",
  START_BACK_RIGHT = "start_back_right",
  START_FORWARD = "start_forward",
  START_LEFT = "start_left",
  START_RIGHT = "start_right",
  RUN = "dance",
  STOP = "dance",
  SPRINT = "sprint",
  ROTATE_LEFT = "rotate_left",
  ROTATE_RIGHT = "rotate_right",
  FALLING = "falling",
  JUMP_IDLE = "jump_idle",
  JUMP_RUNNING = "jump_running",
  DROP_IDLE = "drop_idle",
  DROP_RUNNING_ROLL = "drop_running_roll",
  DROP_RUNNING = "drop_running",
}
